from diffractsim import MonochromaticField

class MoireMonochromaticField(MonochromaticField):

    from .plot_longitudinal_profile import plot_moire_longitudinal_profile_intensity as plot_longitudinal_profile_intensity
